/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.CashierFunctions;
import java.awt.event.KeyEvent;
import com.toedter.calendar.*;

/**
 *
 * @author Farhan
 */
public class AddCashier extends javax.swing.JFrame {
    CashierFunctions cashierFunctions = new CashierFunctions();

    /**
     * Creates new form AddCashier
     */
    public AddCashier() {
        this.setResizable(false);
        cashierFunctions.setCashierFunctions(null, this, null, null, null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        cashierIdField = new javax.swing.JTextField();
        cashierNameField = new javax.swing.JTextField();
        cashierPasswordField = new javax.swing.JPasswordField();
        cashierSalaryField = new javax.swing.JTextField();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Cashier");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(82, 91, 86));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Salary :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 30));

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add_100px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(82, 91, 86));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Add Cashier...");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 170, 40));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Undo_32px.png"))); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        jSeparator9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 210, 10));

        jSeparator10.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, 10));

        jSeparator11.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, 10));

        jSeparator12.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 210, 10));

        cashierIdField.setBackground(new java.awt.Color(82, 91, 86));
        cashierIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierIdField.setForeground(new java.awt.Color(255, 255, 255));
        cashierIdField.setText("Enter ID");
        cashierIdField.setBorder(null);
        cashierIdField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        cashierIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierIdFieldFocusGained(evt);
            }
        });
        jPanel3.add(cashierIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 130, 30));

        cashierNameField.setBackground(new java.awt.Color(82, 91, 86));
        cashierNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierNameField.setForeground(new java.awt.Color(255, 255, 255));
        cashierNameField.setText("Enter Name");
        cashierNameField.setBorder(null);
        cashierNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        cashierNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierNameFieldFocusGained(evt);
            }
        });
        jPanel3.add(cashierNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, 30));

        cashierPasswordField.setBackground(new java.awt.Color(82, 91, 86));
        cashierPasswordField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        cashierPasswordField.setText("password");
        cashierPasswordField.setBorder(null);
        cashierPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierPasswordFieldFocusGained(evt);
            }
        });
        jPanel3.add(cashierPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, 30));

        cashierSalaryField.setBackground(new java.awt.Color(82, 91, 86));
        cashierSalaryField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierSalaryField.setForeground(new java.awt.Color(255, 255, 255));
        cashierSalaryField.setBorder(null);
        cashierSalaryField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(cashierSalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 140, 30));

        add.setBackground(new java.awt.Color(153, 153, 153));
        add.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setText("Add");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });
        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 150, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            CashierOperations cashierOperations = new CashierOperations();
            cashierOperations.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backKeyPressed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        CashierOperations cashierOperations = new CashierOperations();
        cashierOperations.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void cashierIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierIdFieldFocusGained
        cashierIdField.setText("");
    }//GEN-LAST:event_cashierIdFieldFocusGained

    private void cashierNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierNameFieldFocusGained
        cashierNameField.setText("");
    }//GEN-LAST:event_cashierNameFieldFocusGained

    private void cashierPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierPasswordFieldFocusGained
        cashierPasswordField.setText("");
    }//GEN-LAST:event_cashierPasswordFieldFocusGained

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        cashierFunctions.addCashier();
    }//GEN-LAST:event_addActionPerformed

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cashierFunctions.addCashier();
        }
    }//GEN-LAST:event_addKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    public javax.swing.JTextField cashierIdField;
    public javax.swing.JTextField cashierNameField;
    public javax.swing.JPasswordField cashierPasswordField;
    public javax.swing.JTextField cashierSalaryField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
