/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.ProductFunctions;
import java.awt.event.KeyEvent;

/**
 *
 * @author Farhan
 */
public class AddProduct extends javax.swing.JFrame {
    ProductFunctions productFunctions = new ProductFunctions();
    
    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        this.setResizable(false);
        productFunctions.setProductFunctions(this, null, null, null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        productIdField = new javax.swing.JTextField();
        productNameField = new javax.swing.JTextField();
        productPriceField = new javax.swing.JTextField();
        productQuantityField = new javax.swing.JTextField();
        productCompanyIdField = new javax.swing.JComboBox<>();
        productCategoryIdField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Product");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 40));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(82, 91, 86));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Add Product...");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        add.setBackground(new java.awt.Color(153, 153, 153));
        add.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setText("Add");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 110, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Product Category ID :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Manufacture Date :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Expire Date :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Product Company ID :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        jSeparator9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 110, 10));

        jSeparator10.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 130, 10));

        jSeparator11.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 210, 10));

        jSeparator12.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 120, 10));

        jSeparator13.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 160, 10));

        jSeparator14.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 160, 10));

        jSeparator15.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 130, 10));

        jSeparator16.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 130, 10));

        productIdField.setBackground(new java.awt.Color(82, 91, 86));
        productIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productIdField.setForeground(new java.awt.Color(255, 255, 255));
        productIdField.setText("Enter ID");
        productIdField.setBorder(null);
        productIdField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(productIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 130, 30));

        productNameField.setBackground(new java.awt.Color(82, 91, 86));
        productNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productNameField.setForeground(new java.awt.Color(255, 255, 255));
        productNameField.setText("Enter Name");
        productNameField.setBorder(null);
        productNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productNameFieldFocusGained(evt);
            }
        });
        jPanel1.add(productNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 210, 30));

        productPriceField.setBackground(new java.awt.Color(82, 91, 86));
        productPriceField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productPriceField.setForeground(new java.awt.Color(255, 255, 255));
        productPriceField.setBorder(null);
        productPriceField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel1.add(productPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 120, 30));

        productQuantityField.setBackground(new java.awt.Color(82, 91, 86));
        productQuantityField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productQuantityField.setForeground(new java.awt.Color(255, 255, 255));
        productQuantityField.setBorder(null);
        productQuantityField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel1.add(productQuantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 110, 30));

        productCompanyIdField.setBackground(new java.awt.Color(82, 91, 86));
        productCompanyIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productCompanyIdField.setForeground(new java.awt.Color(82, 91, 86));
        productCompanyIdField.setBorder(null);
        productCompanyIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productCompanyIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(productCompanyIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 130, 30));

        productCategoryIdField.setBackground(new java.awt.Color(82, 91, 86));
        productCategoryIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productCategoryIdField.setForeground(new java.awt.Color(82, 91, 86));
        productCategoryIdField.setBorder(null);
        productCategoryIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productCategoryIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(productCategoryIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        ProductOperations productOperations = new ProductOperations();
        productOperations.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            ProductOperations productOperations = new ProductOperations();
        productOperations.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backKeyPressed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        productFunctions.addProduct();
    }//GEN-LAST:event_addActionPerformed

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            productFunctions.addProduct();
        }
    }//GEN-LAST:event_addKeyPressed

    private void productIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productIdFieldFocusGained
        productIdField.setText("");
    }//GEN-LAST:event_productIdFieldFocusGained

    private void productNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productNameFieldFocusGained
        productNameField.setText("");
    }//GEN-LAST:event_productNameFieldFocusGained

    private void productCompanyIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productCompanyIdFieldFocusGained
        productFunctions.productCompanyIdBox();
    }//GEN-LAST:event_productCompanyIdFieldFocusGained

    private void productCategoryIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productCategoryIdFieldFocusGained
        productFunctions.productCategoryIdBox();
    }//GEN-LAST:event_productCategoryIdFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JComboBox<String> productCategoryIdField;
    public javax.swing.JComboBox<String> productCompanyIdField;
    public javax.swing.JTextField productIdField;
    public javax.swing.JTextField productNameField;
    public javax.swing.JTextField productPriceField;
    public javax.swing.JTextField productQuantityField;
    // End of variables declaration//GEN-END:variables
}
