/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.CashierSubmitFunctions;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Farhan
 */
public class Cashier extends javax.swing.JFrame {
    CashierSubmitFunctions cashierSubmitFunctions = new CashierSubmitFunctions();
    
    /**
     * Creates new form Cashier
     */
    public Cashier() {
        this.setResizable(false);
        cashierSubmitFunctions.setCashierSubmitFunctions(this);
        initComponents();
        setLocationRelativeTo(null);
    }
    public void usernameCashier(String userCashier){
        cashierId.setText(userCashier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cashierId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartDetailTable = new javax.swing.JTable();
        add = new javax.swing.JButton();
        transactionTotalField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        cashierNameField = new javax.swing.JTextField();
        transactionIdField = new javax.swing.JTextField();
        productIdField = new javax.swing.JComboBox<>();
        productNameField = new javax.swing.JTextField();
        productPriceField = new javax.swing.JTextField();
        productQuantityField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        customerIdField = new javax.swing.JComboBox<>();
        customerNameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        totalPricePerProductField = new javax.swing.JTextField();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier Panel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(82, 91, 86));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Cashier...");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 40));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 40));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        cashierId.setBackground(new java.awt.Color(82, 91, 86));
        cashierId.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        cashierId.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(cashierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 30, 40));

        jLabel3.setBackground(new java.awt.Color(82, 91, 86));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("ID:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 110));

        submit.setBackground(new java.awt.Color(153, 153, 153));
        submit.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(51, 51, 51));
        submit.setText("Submit");
        submit.setBorder(null);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 660, 110, 40));

        jScrollPane1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        cartDetailTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cartDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Product ID", "Price", "Quantity", "Total Per Product"
            }
        ));
        jScrollPane1.setViewportView(cartDetailTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 700, 120));

        add.setBackground(new java.awt.Color(153, 153, 153));
        add.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setText("Add");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 110, 40));

        transactionTotalField.setEditable(false);
        transactionTotalField.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        transactionTotalField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                transactionTotalFieldFocusGained(evt);
            }
        });
        transactionTotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionTotalFieldActionPerformed(evt);
            }
        });
        jPanel1.add(transactionTotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 180, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Amount");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cashier Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Per Product:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Product Name :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Customer Name :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Transaction ID :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Product ID :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 30));

        jSeparator10.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 130, 10));

        jSeparator13.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 160, 10));

        jSeparator11.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 130, 10));

        jSeparator12.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 140, 10));

        jSeparator14.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 130, 10));

        jSeparator16.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 210, 10));

        jSeparator17.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 120, 10));

        jSeparator9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 120, 10));

        cashierNameField.setEditable(false);
        cashierNameField.setBackground(new java.awt.Color(82, 91, 86));
        cashierNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierNameField.setForeground(new java.awt.Color(255, 255, 255));
        cashierNameField.setBorder(null);
        cashierNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        cashierNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierNameFieldFocusGained(evt);
            }
        });
        jPanel1.add(cashierNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, 30));

        transactionIdField.setBackground(new java.awt.Color(82, 91, 86));
        transactionIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        transactionIdField.setForeground(new java.awt.Color(255, 255, 255));
        transactionIdField.setText("Enter ID");
        transactionIdField.setBorder(null);
        transactionIdField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        transactionIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                transactionIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(transactionIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 30));

        productIdField.setBackground(new java.awt.Color(82, 91, 86));
        productIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productIdField.setForeground(new java.awt.Color(82, 91, 86));
        productIdField.setBorder(null);
        productIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(productIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 30));

        productNameField.setEditable(false);
        productNameField.setBackground(new java.awt.Color(82, 91, 86));
        productNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productNameField.setForeground(new java.awt.Color(255, 255, 255));
        productNameField.setBorder(null);
        productNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productNameFieldFocusGained(evt);
            }
        });
        jPanel1.add(productNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 210, 30));

        productPriceField.setEditable(false);
        productPriceField.setBackground(new java.awt.Color(82, 91, 86));
        productPriceField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productPriceField.setForeground(new java.awt.Color(255, 255, 255));
        productPriceField.setBorder(null);
        productPriceField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productPriceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productPriceFieldFocusGained(evt);
            }
        });
        jPanel1.add(productPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 120, 30));

        productQuantityField.setBackground(new java.awt.Color(82, 91, 86));
        productQuantityField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productQuantityField.setForeground(new java.awt.Color(255, 255, 255));
        productQuantityField.setText("Enter Quantity");
        productQuantityField.setBorder(null);
        productQuantityField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productQuantityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productQuantityFieldFocusGained(evt);
            }
        });
        jPanel1.add(productQuantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 130, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Customer ID :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        jSeparator18.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, 10));

        customerIdField.setBackground(new java.awt.Color(82, 91, 86));
        customerIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        customerIdField.setForeground(new java.awt.Color(82, 91, 86));
        customerIdField.setBorder(null);
        customerIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(customerIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 30));

        customerNameField.setEditable(false);
        customerNameField.setBackground(new java.awt.Color(82, 91, 86));
        customerNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        customerNameField.setForeground(new java.awt.Color(255, 255, 255));
        customerNameField.setBorder(null);
        customerNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        customerNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerNameFieldFocusGained(evt);
            }
        });
        jPanel1.add(customerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 140, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        jSeparator19.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 130, 10));

        totalPricePerProductField.setEditable(false);
        totalPricePerProductField.setBackground(new java.awt.Color(82, 91, 86));
        totalPricePerProductField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        totalPricePerProductField.setForeground(new java.awt.Color(255, 255, 255));
        totalPricePerProductField.setBorder(null);
        totalPricePerProductField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        totalPricePerProductField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalPricePerProductFieldFocusGained(evt);
            }
        });
        jPanel1.add(totalPricePerProductField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 120, 30));

        clear.setBackground(new java.awt.Color(153, 153, 153));
        clear.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(51, 51, 51));
        clear.setText("Clear Table");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearKeyPressed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        LoginCashier loginCashier = new LoginCashier();
        loginCashier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
        LoginCashier loginCashier = new LoginCashier();
        loginCashier.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_backKeyPressed

    private void cashierNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierNameFieldFocusGained
        cashierSubmitFunctions.populateCashierName();
    }//GEN-LAST:event_cashierNameFieldFocusGained

    private void transactionIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transactionIdFieldFocusGained
        transactionIdField.setText("");
    }//GEN-LAST:event_transactionIdFieldFocusGained

    private void productIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productIdFieldFocusGained
         cashierSubmitFunctions.productIdBox();
    }//GEN-LAST:event_productIdFieldFocusGained

    private void productNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productNameFieldFocusGained
        cashierSubmitFunctions.populateProductName();
    }//GEN-LAST:event_productNameFieldFocusGained

    private void productPriceFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productPriceFieldFocusGained
        cashierSubmitFunctions.populateProductPrice();
    }//GEN-LAST:event_productPriceFieldFocusGained

    private void productQuantityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productQuantityFieldFocusGained
        productQuantityField.setText("");
    }//GEN-LAST:event_productQuantityFieldFocusGained

    private void customerIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerIdFieldFocusGained
        cashierSubmitFunctions.customerIdBox();
    }//GEN-LAST:event_customerIdFieldFocusGained

    private void customerNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFieldFocusGained
        cashierSubmitFunctions.populateCustomerName();
    }//GEN-LAST:event_customerNameFieldFocusGained

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cashierSubmitFunctions.addInCart();
        }
    }//GEN-LAST:event_addKeyPressed

    private void transactionTotalFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transactionTotalFieldFocusGained
        cashierSubmitFunctions.saleAmountCashier();
    }//GEN-LAST:event_transactionTotalFieldFocusGained

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        cashierSubmitFunctions.addInCart();
    }//GEN-LAST:event_addActionPerformed

    private void totalPricePerProductFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalPricePerProductFieldFocusGained
        cashierSubmitFunctions.totalPricePerProduct();
    }//GEN-LAST:event_totalPricePerProductFieldFocusGained

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       
        cashierSubmitFunctions.submitTransaction();
        cashierSubmitFunctions.submitDetail();
    }//GEN-LAST:event_submitActionPerformed

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cashierSubmitFunctions.submitTransaction();
            cashierSubmitFunctions.submitDetail();
        }
    }//GEN-LAST:event_submitKeyPressed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        cashierSubmitFunctions.clearTable();
    }//GEN-LAST:event_clearActionPerformed

    private void clearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cashierSubmitFunctions.clearTable();
        }
    }//GEN-LAST:event_clearKeyPressed

    private void transactionTotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionTotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionTotalFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    public javax.swing.JTable cartDetailTable;
    public javax.swing.JLabel cashierId;
    public javax.swing.JTextField cashierNameField;
    private javax.swing.JButton clear;
    public javax.swing.JComboBox<String> customerIdField;
    public javax.swing.JTextField customerNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JComboBox<String> productIdField;
    public javax.swing.JTextField productNameField;
    public javax.swing.JTextField productPriceField;
    public javax.swing.JTextField productQuantityField;
    private javax.swing.JButton submit;
    public javax.swing.JTextField totalPricePerProductField;
    public javax.swing.JTextField transactionIdField;
    public javax.swing.JTextField transactionTotalField;
    // End of variables declaration//GEN-END:variables
}
