/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.KeyEvent;

/**
 *
 * @author Farhan
 */
public class CompanyOperations extends javax.swing.JFrame {

    /**
     * Creates new form CompanyOperations
     */
    public CompanyOperations() {
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        addCompany = new javax.swing.JButton();
        deleteCompany = new javax.swing.JButton();
        viewCompany = new javax.swing.JButton();
        searchUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company Operations");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(82, 91, 86));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Company...");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Company_100px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Undo_32px.png"))); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        addCompany.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        addCompany.setForeground(new java.awt.Color(19, 34, 38));
        addCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add_100px.png"))); // NOI18N
        addCompany.setText("Add");
        addCompany.setBorder(null);
        addCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompanyActionPerformed(evt);
            }
        });
        addCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addCompanyKeyPressed(evt);
            }
        });
        jPanel1.add(addCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 120));

        deleteCompany.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        deleteCompany.setForeground(new java.awt.Color(19, 34, 38));
        deleteCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete_100px.png"))); // NOI18N
        deleteCompany.setText("Delete");
        deleteCompany.setBorder(null);
        deleteCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompanyActionPerformed(evt);
            }
        });
        deleteCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteCompanyKeyPressed(evt);
            }
        });
        jPanel1.add(deleteCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 210, 120));

        viewCompany.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        viewCompany.setForeground(new java.awt.Color(19, 34, 38));
        viewCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View_100px.png"))); // NOI18N
        viewCompany.setText("View");
        viewCompany.setBorder(null);
        viewCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCompanyActionPerformed(evt);
            }
        });
        viewCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewCompanyKeyPressed(evt);
            }
        });
        jPanel1.add(viewCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 120));

        searchUpdate.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        searchUpdate.setForeground(new java.awt.Color(19, 34, 38));
        searchUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_and_Update_100px.png"))); // NOI18N
        searchUpdate.setText("Search Update");
        searchUpdate.setBorder(null);
        searchUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUpdateActionPerformed(evt);
            }
        });
        searchUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchUpdateKeyPressed(evt);
            }
        });
        jPanel1.add(searchUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 210, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompanyActionPerformed
            AddCompany AddCompany = new AddCompany();
            AddCompany.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_addCompanyActionPerformed

    private void addCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addCompanyKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            AddCompany AddCompany = new AddCompany();
            AddCompany.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_addCompanyKeyPressed

    private void deleteCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompanyActionPerformed
            DeleteCompany DeleteCompany = new DeleteCompany();
            DeleteCompany.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_deleteCompanyActionPerformed

    private void deleteCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deleteCompanyKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            DeleteCompany DeleteCompany = new DeleteCompany();
            DeleteCompany.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_deleteCompanyKeyPressed

    private void viewCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCompanyActionPerformed
            ViewCompany ViewCompany = new ViewCompany();
            ViewCompany.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_viewCompanyActionPerformed

    private void viewCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewCompanyKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ViewCompany ViewCompany = new ViewCompany();
            ViewCompany.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_viewCompanyKeyPressed

    private void searchUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUpdateActionPerformed
        SearchUpdateCompany searchAndUpdate = new SearchUpdateCompany();
        searchAndUpdate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchUpdateActionPerformed

    private void searchUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchUpdateKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        SearchUpdateCompany searchAndUpdate = new SearchUpdateCompany();
        searchAndUpdate.setVisible(true);
        this.dispose();    
        }
    }//GEN-LAST:event_searchUpdateKeyPressed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Admin admin = new Admin();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            Admin admin = new Admin();
            admin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyOperations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompany;
    private javax.swing.JButton back;
    private javax.swing.JButton deleteCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton searchUpdate;
    private javax.swing.JButton viewCompany;
    // End of variables declaration//GEN-END:variables
}
