/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.ProductFunctions;
import java.awt.event.KeyEvent;

/**
 *
 * @author Farhan
 */
public class SearchUpdateProduct extends javax.swing.JFrame {
    ProductFunctions productFunctions = new ProductFunctions();
    
    /**
     * Creates new form SearchUpdateProduct
     */
    public SearchUpdateProduct() {
        this.setResizable(false);
        productFunctions.setProductFunctions(null, null, null, this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        productSearchIdField = new javax.swing.JComboBox<>();
        productSearchNameField = new javax.swing.JTextField();
        productSearchPriceField = new javax.swing.JTextField();
        productSearchQuantityField = new javax.swing.JTextField();
        productSearchCompanyIdField = new javax.swing.JTextField();
        productSearchCategoryIdField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search and Update Product");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(82, 91, 86));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Search and Update Product...");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 40));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 40));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        search.setBackground(new java.awt.Color(153, 153, 153));
        search.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setText("Search");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 110, 40));

        update.setBackground(new java.awt.Color(153, 153, 153));
        update.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("Update");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateKeyPressed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 110, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Manufacture Date :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Expire Date :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Product Company ID :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Product Category ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 30));

        jSeparator9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 110, 10));

        jSeparator10.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, 10));

        jSeparator11.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 210, 10));

        jSeparator12.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 120, 10));

        jSeparator13.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 160, 10));

        jSeparator14.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 160, 10));

        jSeparator15.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 130, 10));

        jSeparator16.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 130, 10));

        productSearchIdField.setBackground(new java.awt.Color(82, 91, 86));
        productSearchIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productSearchIdField.setForeground(new java.awt.Color(82, 91, 86));
        productSearchIdField.setBorder(null);
        productSearchIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productSearchIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(productSearchIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 130, 40));

        productSearchNameField.setBackground(new java.awt.Color(82, 91, 86));
        productSearchNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productSearchNameField.setForeground(new java.awt.Color(255, 255, 255));
        productSearchNameField.setBorder(null);
        productSearchNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productSearchNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productSearchNameFieldFocusGained(evt);
            }
        });
        jPanel1.add(productSearchNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 210, 30));

        productSearchPriceField.setBackground(new java.awt.Color(82, 91, 86));
        productSearchPriceField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productSearchPriceField.setForeground(new java.awt.Color(255, 255, 255));
        productSearchPriceField.setBorder(null);
        productSearchPriceField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productSearchPriceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productSearchPriceFieldFocusGained(evt);
            }
        });
        jPanel1.add(productSearchPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 120, 30));

        productSearchQuantityField.setBackground(new java.awt.Color(82, 91, 86));
        productSearchQuantityField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productSearchQuantityField.setForeground(new java.awt.Color(255, 255, 255));
        productSearchQuantityField.setBorder(null);
        productSearchQuantityField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productSearchQuantityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productSearchQuantityFieldFocusGained(evt);
            }
        });
        jPanel1.add(productSearchQuantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 110, 30));

        productSearchCompanyIdField.setBackground(new java.awt.Color(82, 91, 86));
        productSearchCompanyIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productSearchCompanyIdField.setForeground(new java.awt.Color(255, 255, 255));
        productSearchCompanyIdField.setBorder(null);
        productSearchCompanyIdField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productSearchCompanyIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productSearchCompanyIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(productSearchCompanyIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 130, 30));

        productSearchCategoryIdField.setBackground(new java.awt.Color(82, 91, 86));
        productSearchCategoryIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productSearchCategoryIdField.setForeground(new java.awt.Color(255, 255, 255));
        productSearchCategoryIdField.setBorder(null);
        productSearchCategoryIdField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        productSearchCategoryIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productSearchCategoryIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(productSearchCategoryIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        ProductOperations productOperations = new ProductOperations();
        productOperations.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            ProductOperations productOperations = new ProductOperations();
            productOperations.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backKeyPressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        productFunctions.searchProduct();
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        productFunctions.searchProduct();
        }
    }//GEN-LAST:event_searchKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        productFunctions.updateProduct();
    }//GEN-LAST:event_updateActionPerformed

    private void updateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        productFunctions.updateProduct();
        }
    }//GEN-LAST:event_updateKeyPressed

    private void productSearchIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productSearchIdFieldFocusGained
        productFunctions.productSearchBox();
    }//GEN-LAST:event_productSearchIdFieldFocusGained

    private void productSearchNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productSearchNameFieldFocusGained
        productSearchNameField.setText("");
    }//GEN-LAST:event_productSearchNameFieldFocusGained

    private void productSearchPriceFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productSearchPriceFieldFocusGained
        productSearchPriceField.setText("");
    }//GEN-LAST:event_productSearchPriceFieldFocusGained

    private void productSearchQuantityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productSearchQuantityFieldFocusGained
        productSearchQuantityField.setText("");
    }//GEN-LAST:event_productSearchQuantityFieldFocusGained

    private void productSearchCompanyIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productSearchCompanyIdFieldFocusGained
        productSearchCompanyIdField.setText("");
    }//GEN-LAST:event_productSearchCompanyIdFieldFocusGained

    private void productSearchCategoryIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productSearchCategoryIdFieldFocusGained
        productSearchCategoryIdField.setText("");
    }//GEN-LAST:event_productSearchCategoryIdFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField productSearchCategoryIdField;
    public javax.swing.JTextField productSearchCompanyIdField;
    public javax.swing.JComboBox<String> productSearchIdField;
    public javax.swing.JTextField productSearchNameField;
    public javax.swing.JTextField productSearchPriceField;
    public javax.swing.JTextField productSearchQuantityField;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
