/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.CashierFunctions;
import java.awt.event.KeyEvent;

/**
 *
 * @author Farhan
 */
public class SearchUpdateCashier extends javax.swing.JFrame {
    CashierFunctions cashierFunctions = new CashierFunctions();
    
    /**
     * Creates new form SearchUpdateCashier
     */
    public SearchUpdateCashier() {
        this.setResizable(false);
        cashierFunctions.setCashierFunctions(null, null, null, null, this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        cashierSearchIdField = new javax.swing.JComboBox<>();
        cashierSearchNameField = new javax.swing.JTextField();
        cashierSearchPasswordField = new javax.swing.JPasswordField();
        cashierSearchSalaryField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search and Update Cashier");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 40));

        jLabel2.setBackground(new java.awt.Color(82, 91, 86));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Search and Update Cashier...");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 350, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        search.setBackground(new java.awt.Color(153, 153, 153));
        search.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setText("Search");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 110, 40));

        update.setBackground(new java.awt.Color(153, 153, 153));
        update.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("Update");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateKeyPressed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 110, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Salary :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hire Date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 30));

        jSeparator9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, 10));

        jSeparator10.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, 10));

        jSeparator11.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, 10));

        jSeparator12.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 140, 10));

        jSeparator8.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 160, 10));

        cashierSearchIdField.setBackground(new java.awt.Color(82, 91, 86));
        cashierSearchIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierSearchIdField.setForeground(new java.awt.Color(82, 91, 86));
        cashierSearchIdField.setBorder(null);
        cashierSearchIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierSearchIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(cashierSearchIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 40));

        cashierSearchNameField.setBackground(new java.awt.Color(82, 91, 86));
        cashierSearchNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierSearchNameField.setForeground(new java.awt.Color(255, 255, 255));
        cashierSearchNameField.setBorder(null);
        cashierSearchNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        cashierSearchNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierSearchNameFieldFocusGained(evt);
            }
        });
        jPanel1.add(cashierSearchNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, 30));

        cashierSearchPasswordField.setBackground(new java.awt.Color(82, 91, 86));
        cashierSearchPasswordField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierSearchPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        cashierSearchPasswordField.setBorder(null);
        cashierSearchPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierSearchPasswordFieldFocusGained(evt);
            }
        });
        jPanel1.add(cashierSearchPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, 30));

        cashierSearchSalaryField.setBackground(new java.awt.Color(82, 91, 86));
        cashierSearchSalaryField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cashierSearchSalaryField.setForeground(new java.awt.Color(255, 255, 255));
        cashierSearchSalaryField.setBorder(null);
        cashierSearchSalaryField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        cashierSearchSalaryField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cashierSearchSalaryFieldFocusGained(evt);
            }
        });
        jPanel1.add(cashierSearchSalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        CashierOperations cashierOperations = new CashierOperations();
        cashierOperations.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
        CashierOperations cashierOperations = new CashierOperations();
        cashierOperations.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_backKeyPressed

    private void cashierSearchIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierSearchIdFieldFocusGained
        cashierFunctions.cashierSearchBox();
    }//GEN-LAST:event_cashierSearchIdFieldFocusGained

    private void cashierSearchNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierSearchNameFieldFocusGained
        cashierSearchNameField.setText("");
    }//GEN-LAST:event_cashierSearchNameFieldFocusGained

    private void cashierSearchPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierSearchPasswordFieldFocusGained
        cashierSearchPasswordField.setText("");
    }//GEN-LAST:event_cashierSearchPasswordFieldFocusGained

    private void cashierSearchSalaryFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierSearchSalaryFieldFocusGained
        cashierSearchSalaryField.setText("");
    }//GEN-LAST:event_cashierSearchSalaryFieldFocusGained

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        cashierFunctions.searchCashier();
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        cashierFunctions.searchCashier();
        }
    }//GEN-LAST:event_searchKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        cashierFunctions.updateCashier();
    }//GEN-LAST:event_updateActionPerformed

    private void updateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cashierFunctions.updateCashier();
        }
    }//GEN-LAST:event_updateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUpdateCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    public javax.swing.JComboBox<String> cashierSearchIdField;
    public javax.swing.JTextField cashierSearchNameField;
    public javax.swing.JPasswordField cashierSearchPasswordField;
    public javax.swing.JTextField cashierSearchSalaryField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
