/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.CustomerFunctions;
import java.awt.event.KeyEvent;

/**
 *
 * @author Farhan
 */
public class SignupCustomer extends javax.swing.JFrame {
    CustomerFunctions customerFunctions = new CustomerFunctions();
    
    /**
     * Creates new form SignupCustomer
     */
    public SignupCustomer() {
        this.setResizable(false);
        customerFunctions.setCustomerFunctions(null, this, null, null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        signupCustomerIdField = new javax.swing.JTextField();
        signupCustomerPasswordField = new javax.swing.JPasswordField();
        signupCustomerNameField = new javax.swing.JTextField();
        signupCustomerEmailField = new javax.swing.JTextField();
        signupCustomerAgeField = new javax.swing.JTextField();
        signupCustomerAddressField = new javax.swing.JTextField();
        signupCustomerGenderField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup Customer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Undo_32px.png"))); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customer_100px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(82, 91, 86));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Sign Up Customer");
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 230, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        signup.setBackground(new java.awt.Color(153, 153, 153));
        signup.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signup.setForeground(new java.awt.Color(51, 51, 51));
        signup.setText("SignUp");
        signup.setBorder(null);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        signup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signupKeyPressed(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 110, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Age :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("E-mail:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Password :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 30));

        jSeparator9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 280, 10));

        jSeparator10.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, 10));

        jSeparator11.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 190, 10));

        jSeparator12.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 190, 10));

        jSeparator13.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 120, 10));

        jSeparator14.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 90, 10));

        jSeparator15.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 280, 10));

        signupCustomerIdField.setBackground(new java.awt.Color(82, 91, 86));
        signupCustomerIdField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signupCustomerIdField.setForeground(new java.awt.Color(255, 255, 255));
        signupCustomerIdField.setText("Enter ID");
        signupCustomerIdField.setBorder(null);
        signupCustomerIdField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        signupCustomerIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signupCustomerIdFieldFocusGained(evt);
            }
        });
        jPanel1.add(signupCustomerIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, 30));

        signupCustomerPasswordField.setBackground(new java.awt.Color(82, 91, 86));
        signupCustomerPasswordField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signupCustomerPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        signupCustomerPasswordField.setText("password");
        signupCustomerPasswordField.setBorder(null);
        signupCustomerPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signupCustomerPasswordFieldFocusGained(evt);
            }
        });
        jPanel1.add(signupCustomerPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, 30));

        signupCustomerNameField.setBackground(new java.awt.Color(82, 91, 86));
        signupCustomerNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signupCustomerNameField.setForeground(new java.awt.Color(255, 255, 255));
        signupCustomerNameField.setText("Enter Name");
        signupCustomerNameField.setBorder(null);
        signupCustomerNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        signupCustomerNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signupCustomerNameFieldFocusGained(evt);
            }
        });
        jPanel1.add(signupCustomerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 190, 30));

        signupCustomerEmailField.setBackground(new java.awt.Color(82, 91, 86));
        signupCustomerEmailField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signupCustomerEmailField.setForeground(new java.awt.Color(255, 255, 255));
        signupCustomerEmailField.setText("Enter Email");
        signupCustomerEmailField.setBorder(null);
        signupCustomerEmailField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        signupCustomerEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signupCustomerEmailFieldFocusGained(evt);
            }
        });
        jPanel1.add(signupCustomerEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 280, 30));

        signupCustomerAgeField.setBackground(new java.awt.Color(82, 91, 86));
        signupCustomerAgeField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signupCustomerAgeField.setForeground(new java.awt.Color(255, 255, 255));
        signupCustomerAgeField.setText("Enter Age");
        signupCustomerAgeField.setBorder(null);
        signupCustomerAgeField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        signupCustomerAgeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signupCustomerAgeFieldFocusGained(evt);
            }
        });
        jPanel1.add(signupCustomerAgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 90, 30));

        signupCustomerAddressField.setBackground(new java.awt.Color(82, 91, 86));
        signupCustomerAddressField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signupCustomerAddressField.setForeground(new java.awt.Color(255, 255, 255));
        signupCustomerAddressField.setText("Enter Address");
        signupCustomerAddressField.setBorder(null);
        signupCustomerAddressField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        signupCustomerAddressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signupCustomerAddressFieldFocusGained(evt);
            }
        });
        jPanel1.add(signupCustomerAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 280, 30));

        signupCustomerGenderField.setBackground(new java.awt.Color(82, 91, 86));
        signupCustomerGenderField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        signupCustomerGenderField.setForeground(new java.awt.Color(82, 91, 86));
        signupCustomerGenderField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        signupCustomerGenderField.setBorder(null);
        jPanel1.add(signupCustomerGenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        LoginCustomer loginCustomer = new LoginCustomer();
        loginCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            LoginCustomer loginCustomer = new LoginCustomer();
            loginCustomer.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backKeyPressed

    private void signupCustomerIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signupCustomerIdFieldFocusGained
        signupCustomerIdField.setText("");
    }//GEN-LAST:event_signupCustomerIdFieldFocusGained

    private void signupCustomerPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signupCustomerPasswordFieldFocusGained
        signupCustomerPasswordField.setText("");
    }//GEN-LAST:event_signupCustomerPasswordFieldFocusGained

    private void signupCustomerNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signupCustomerNameFieldFocusGained
        signupCustomerNameField.setText("");
    }//GEN-LAST:event_signupCustomerNameFieldFocusGained

    private void signupCustomerEmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signupCustomerEmailFieldFocusGained
         signupCustomerEmailField.setText("");
    }//GEN-LAST:event_signupCustomerEmailFieldFocusGained

    private void signupCustomerAgeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signupCustomerAgeFieldFocusGained
        signupCustomerAgeField.setText("");
    }//GEN-LAST:event_signupCustomerAgeFieldFocusGained

    private void signupCustomerAddressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signupCustomerAddressFieldFocusGained
        signupCustomerAddressField.setText("");
    }//GEN-LAST:event_signupCustomerAddressFieldFocusGained

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        customerFunctions.addCustomer();
    }//GEN-LAST:event_signupActionPerformed

    private void signupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        customerFunctions.addCustomer();
        }
    }//GEN-LAST:event_signupKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton signup;
    public javax.swing.JTextField signupCustomerAddressField;
    public javax.swing.JTextField signupCustomerAgeField;
    public javax.swing.JTextField signupCustomerEmailField;
    public javax.swing.JComboBox<String> signupCustomerGenderField;
    public javax.swing.JTextField signupCustomerIdField;
    public javax.swing.JTextField signupCustomerNameField;
    public javax.swing.JPasswordField signupCustomerPasswordField;
    // End of variables declaration//GEN-END:variables
}
