/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.KeyEvent;

/**
 *
 * @author Farhan
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        cashierButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 91, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 34, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(82, 91, 86));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Mart Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 40));

        jSeparator3.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 540, 10));

        jSeparator2.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 500, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mart_100px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 180));

        adminButton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        adminButton.setForeground(new java.awt.Color(19, 34, 38));
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Admin_100px.png"))); // NOI18N
        adminButton.setText("Admin");
        adminButton.setBorder(null);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        adminButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminButtonKeyPressed(evt);
            }
        });
        jPanel1.add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 110));

        cashierButton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        cashierButton.setForeground(new java.awt.Color(19, 34, 38));
        cashierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cashier_100px.png"))); // NOI18N
        cashierButton.setText("Cashier");
        cashierButton.setBorder(null);
        cashierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButtonActionPerformed(evt);
            }
        });
        cashierButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cashierButtonKeyPressed(evt);
            }
        });
        jPanel1.add(cashierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 210, 110));

        customerButton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        customerButton.setForeground(new java.awt.Color(19, 34, 38));
        customerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customer_100px.png"))); // NOI18N
        customerButton.setText("Customer");
        customerButton.setBorder(null);
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        customerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerButtonKeyPressed(evt);
            }
        });
        jPanel1.add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        LoginAdmin loginAdmin = new LoginAdmin();
        loginAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void cashierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButtonActionPerformed
        LoginCashier loginCashier = new LoginCashier();
        loginCashier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cashierButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        LoginCustomer loginCustomer = new LoginCustomer();
        loginCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerButtonActionPerformed

    private void adminButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){   
          LoginAdmin loginAdmin = new LoginAdmin();
            loginAdmin.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_adminButtonKeyPressed

    private void cashierButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashierButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){   
          LoginCashier loginCashier = new LoginCashier();
            loginCashier.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_cashierButtonKeyPressed

    private void customerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){   
          LoginCustomer loginCustomer = new LoginCustomer();
            loginCustomer.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_customerButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton cashierButton;
    private javax.swing.JButton customerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
